"$schema" = "./kaledis.schema.json"
experimental_hmr = true

[project]
name = "game_example"
love_path = "C:/Program Files/LOVE"
src_path="src"
detect_modules=true

[window]
title = "Untitled"

[audio]
